config/routes.rb
Rails.application.routes.draw do
  resources :table_data

end

app/models/api.rb
class Api < ActiveRecord::Base
end

app/models/item_table.rb
class ItemTable < ActiveRecord::Base
end

app/models/table_datum.rb
class TableDatum < ActiveRecord::Base
  
  
  
  
end

app/models/table_item.rb
class TableItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/table_data_controller.rb
class TableDataController < ApplicationController
  before_action :set_table_datum, only: [:show, :edit, :update, :destroy]

  # GET /table_data
  # GET /table_data.json
  def index
    @table_data = TableDatum.all
  end

  # GET /table_data/1
  # GET /table_data/1.json
  def show
  end

  # GET /table_data/new
  def new
    @table_datum = TableDatum.new
  end

  # GET /table_data/1/edit
  def edit
  end

  # POST /table_data
  # POST /table_data.json
  def create
    @table_datum = TableDatum.new(table_datum_params)

    respond_to do |format|
      if @table_datum.save
        format.html { redirect_to @table_datum, notice: 'Table datum was successfully created.' }
        format.json { render :show, status: :created, location: @table_datum }
      else
        format.html { render :new }
        format.json { render json: @table_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /table_data/1
  # PATCH/PUT /table_data/1.json
  def update
    respond_to do |format|
      if @table_datum.update(table_datum_params)
        format.html { redirect_to @table_datum, notice: 'Table datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @table_datum }
      else
        format.html { render :edit }
        format.json { render json: @table_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /table_data/1
  # DELETE /table_data/1.json
  def destroy
    @table_datum.destroy
    respond_to do |format|
      format.html { redirect_to table_data_url, notice: 'Table datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table_datum
      @table_datum = TableDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_datum_params
      params.require(:table_datum).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/table_data_helper.rb
module TableDataHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Mega Table
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
 
  body
    = yield

app/views/table_data/_form.html.slim
= simple_form_for(@table_datum) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/table_data/edit.html.slim
h1 Editing table_datum

== render 'form'

= link_to 'Show', @table_datum
'|
= link_to 'Back', table_data_path

app/views/table_data/index.html.slim
h1 Listing table_data

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @table_data.each do |table_datum|
      tr
        td = table_datum.name
        td = link_to 'Show', table_datum
        td = link_to 'Edit', edit_table_datum_path(table_datum)
        td = link_to 'Destroy', table_datum, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Table datum', new_table_datum_path

app/views/table_data/new.html.slim
h1 New table_datum

== render 'form'

= link_to 'Back', table_data_path

app/views/table_data/show.html.slim
p#notice = notice

p
  strong Name:
  = @table_datum.name

= link_to 'Edit', edit_table_datum_path(@table_datum)
'|
= link_to 'Back', table_data_path